/*
 * File: app/view/AddHardwareTypeViewModel.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RobotDriver.view.AddHardwareTypeViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.addhardwaretype',

    requires: [
        'Ext.data.Store',
        'Ext.data.field.Field'
    ],

    stores: {
        hardwareTypeStore: {
            data: [
                [
                    'servo',
                    'Servo'
                ],
                [
                    'motordriver',
                    'Motor Driver'
                ],
                [
                    'gpio',
                    'GPIO'
                ],
                [
                    'i2c',
                    'I2C Device'
                ]
            ],
            fields: [
                {
                    name: 'value'
                },
                {
                    name: 'display'
                }
            ]
        }
    }

});