/*
 * File: app/view/ControlSlider.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RobotDriver.view.ControlSlider', {
    extend: 'Ext.form.Panel',
    alias: 'widget.controlslider',

    requires: [
        'RobotDriver.view.HardwareServoViewModel3',
        'RobotDriver.view.ControlHardwareCombo',
        'Ext.field.Text',
        'Ext.Spacer',
        'Ext.Button',
        'Ext.Panel',
        'Ext.field.Slider'
    ],

    viewModel: {
        type: 'controlslider'
    },
    border: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'start'
            },
            items: [
                {
                    xtype: 'controlhardwarecombo',
                    itemId: 'hardware',
                    listeners: {
                        select: 'onHardwareSelect'
                    }
                },
                {
                    xtype: 'textfield',
                    enableKeyEvents: true,
                    itemId: 'name',
                    name: 'name',
                    margin: 10,
                    label: 'Name',
                    labelWidth: 50,
                    autoComplete: false,
                    clearable: false,
                    placeholder: 'Name',
                    listeners: {
                        change: 'onMytextfield3Change'
                    }
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    margin: '10 10 0 0',
                    iconCls: 'x-fa fa-trash',
                    text: 'Delete',
                    listeners: {
                        tap: 'onMybutton9Tap'
                    }
                }
            ]
        },
        {
            xtype: 'panel',
            padding: '20 30',
            layout: 'vbox',
            title: 'Preview',
            items: [
                {
                    xtype: 'sliderfield',
                    itemId: 'sliderPreview',
                    label: 'Name',
                    labelWidth: 150,
                    readOnly: true,
                    listeners: {
                        dragstart: 'onSliderPreviewDragStart',
                        dragend: 'onSliderPreviewDragEnd',
                        mousedown: 'onSliderPreviewMouseDown'
                    }
                }
            ]
        }
    ],
    listeners: {
        painted: 'onFormpanelPainted'
    },

    onHardwareSelect: function(selection) {
        if(selection !== null && this.queryById('name').getValue() === ''){
            this.queryById('name').setValue(selection.data.name);
        }
    },

    onMytextfield3Change: function(field, newValue, oldValue, eOpts) {
        this.queryById('sliderPreview').setLabel(newValue);
    },

    onMybutton9Tap: function(button, e, eOpts) {
        console.log('delete servo');
        console.log(this);

        //this.hide({type:'fade'});
        //Ext.defer(function(){
            Ext.destroy(this);
        //},400,this);
    },

    onSliderPreviewDragStart: function(sliderfield, sl, thumb, value, e, eOpts) {
        console.log('drag start');
    },

    onSliderPreviewDragEnd: function(sliderfield, sl, thumb, value, e, eOpts) {
        console.log('drag end');
    },

    onSliderPreviewMouseDown: function(e, eOpts) {
        console.log('mouse down');
    },

    onFormpanelPainted: function(sender, element, eOpts) {


        // console.log(this.hardwareStore);
        // let hardwareField = this.queryById('hardware');
        // console.log(hardwareField);
        // hardwareField.setStore(this.hardwareStore);
        // console.log(hardwareField.getStore());
    },

    getConfigValues: function() {
        console.log('slider - getConfigValues');

        let values = this.getValues();
        values.type='slider';

        values.hardware = this.queryById('hardware').getHardwareId();

        console.log(values);

        return values;
    }

});