/*
 * File: app/view/ControlHardwareCombo.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RobotDriver.view.ControlHardwareCombo', {
    extend: 'Ext.Container',
    alias: 'widget.controlhardwarecombo',

    requires: [
        'RobotDriver.view.ControlHardwareComboViewModel',
        'Ext.field.ComboBox',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'controlhardwarecombo'
    },
    itemId: 'hardware',
    padding: 10,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'combobox',
            itemId: 'hardwareCombo',
            width: 295,
            label: 'Hardware',
            labelWidth: 80,
            matchFieldWidth: false,
            displayField: 'display',
            itemTpl: [
                '{type} {name}'
            ],
            valueField: 'hardwareId',
            forceSelection: true,
            minChars: 1,
            queryCaching: false,
            queryMode: 'local',
            typeAhead: true,
            bind: {
                store: '{hardwareComboStore}'
            },
            listeners: {
                select: 'onHardwareSelect',
                change: 'onHardwareComboChange'
            }
        },
        {

        }
    ],

    onHardwareSelect: function(combobox, newValue, oldValue, eOpts) {
        console.log('select!', newValue);
        this.fireEvent('select',newValue);
    },

    onHardwareComboChange: function(combobox, newValue, oldValue, eOpts) {
        console.log('hardware combo change!');
        console.log(combobox, newValue);
    },

    syncHardwareStore: function(store) {
        let hardwareStore = this.getViewModel().getStore('hardwareComboStore');

        hardwareStore.removeAll();

        store.getData().each(function(rec){
            let newRec = rec.clone();
            newRec.set('display',newRec.get('type')+' '+newRec.get('name'));
            hardwareStore.add(newRec);
        },this);
    },

    getHardwareId: function() {
        console.log('control hardware get value');
        let sel = this.queryById('hardwareCombo').getSelection();

        let value = null;

        if(sel !== null){
            //value = sel.data;
            value = {
                type: sel.data.type,
                //devNum: sel.data.devNum,
                name: sel.data.name,
                display: sel.data.display,
                hardwareId: sel.data.hardwareId
            };
        }

        return value;
    },

    setHardwareId: function(hardwareId) {
        console.log('control setHardwareId');
        console.log(hardwareId);
        console.log(this.getViewModel().getStore('hardwareComboStore'));
        console.log(hardwareId);

        this.queryById('hardwareCombo').setValue(hardwareId);
    }

});