/*
 * File: app/view/GamepadItemMap.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RobotDriver.view.GamepadItemMap', {
    extend: 'Ext.Panel',
    alias: 'widget.gamepaditemmap',

    requires: [
        'RobotDriver.view.GamepadItemMapViewModel',
        'Ext.Container',
        'Ext.Button',
        'Ext.field.ComboBox'
    ],

    viewModel: {
        type: 'gamepaditemmap'
    },
    border: true,
    margin: '6 0 0 0',
    padding: '0 0 6 10',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'start'
    },
    items: [
        {
            xtype: 'container',
            height: 32,
            userCls: 'mapped-to',
            margin: '10 0 0 0',
            layout: {
                type: 'hbox',
                align: 'start'
            },
            items: [
                {
                    xtype: 'container',
                    width: 100,
                    html: 'Mapped To:',
                    margin: '6 0 0 10'
                },
                {
                    xtype: 'container',
                    itemId: 'mappedTo',
                    html: '<font color="red">Press Button/Move Axis On Controller</font>',
                    margin: '6 0 0 0'
                },
                {
                    xtype: 'button',
                    hidden: true,
                    itemId: 'remap',
                    margin: '0 0 0 10',
                    iconCls: 'x-fa fa-pencil-square-o',
                    text: 'Remap',
                    listeners: {
                        tap: 'onMybuttonTap'
                    }
                }
            ]
        },
        {
            xtype: 'combobox',
            disabled: true,
            itemId: 'control',
            name: 'control',
            width: 367,
            label: 'Control',
            labelTextAlign: 'right',
            labelWidth: 110,
            displayField: 'name',
            valueField: 'controlId',
            bind: {
                store: '{controlStore}'
            }
        },
        {
            xtype: 'textfield',
            itemId: 'name',
            name: 'name',
            label: 'Name (optional)',
            labelWidth: 110
        }
    ],

    onMybuttonTap: function(button, e, eOpts) {
        this.fireEvent('remap', this);
        this.setMapping(false);
    },

    setMapping: function(gamepadId, gamepadIndex, mapType, mapIndex) {
        if(gamepadId === false){
            this.mapping = false;
            this.queryById('remap').hide();

            this.queryById('control').setValue(null);
            this.queryById('control').disable();

            this.queryById('mappedTo').setHtml('<font color="red">Press Button/Move Axis On Controller</font>');
            return;
        }

        this.mapping = {
            gamepadId:gamepadId,
            gamepadIndex:gamepadIndex,
            mapType:mapType,
            mapIndex:mapIndex
        };
        console.log('insanity');
        this.queryById('mappedTo').setHtml(gamepadId + " "+mapType+" #"+ (parseInt(mapIndex)+1) );
        this.queryById('control').enable();
        this.queryById('remap').show();
    },

    getMapping: function() {
        return this.mapping ? this.mapping : false;
    },

    setControlStoreData: function() {

    }

});