/*
 * File: app/view/liveController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.5.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.5.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('RobotDriver.view.liveController', {
    extend: 'Ext.Container',
    alias: 'widget.livecontroller',

    requires: [
        'RobotDriver.view.liveControllerViewModel'
    ],

    viewModel: {
        type: 'livecontroller'
    },
    defaultListenerScope: true,

    listeners: {
        painted: 'onContainerPainted'
    },

    onContainerPainted: function(sender, element, eOpts) {
        if(this.init){
            return;
        }else{
            this.init = true;
        }

        this.activeGamepads = {};
        this.gamepadStates = {};

        var gamepadUpdate = navigator.getGamepads();
        for(var i=0; i<9; i++){
            if(gamepadUpdate[i] && gamepadUpdate[i].id){
                this.gamepadConnected({gamepad: gamepadUpdate[i]});
            }
        }

        window.addEventListener("gamepadconnected", this.gamepadConnected.bind(this));
        window.addEventListener("gamepaddisconnected", this.gamepadDisconnected.bind(this));

        this.gamePadLoop = false;
        this.startControllerLoop();
    },

    loadConfig: function(config) {
        this.mappedGamepads = config;
    },

    startControllerLoop: function() {
        if(this.gamePadLoop !== false){
            return;
        }
        this.gamePadLoop = setInterval(this.gamepadPoll.bind(this), 75);
    },

    stopControllerLoop: function() {
        if(this.gamePadLoop === false){
            return;
        }
        clearInterval(this.gamePadLoop);
        this.gamePadLoop = false;
    },

    gamepadConnected: function(e) {
        let gx = e.gamepad.index+e.gamepad.id;

        this.activeGamepads[gx] = e.gamepad;

        this.fireEvent('gamepadConnect', e.gamepad);

        this.gamepadStates[gx] = this.getGamepadState(e.gamepad);
    },

    gamepadDisconnected: function(e) {
        let gx = e.gamepad.index+e.gamepad.id;

        delete this.activeGamepads[gx];
        delete this.gamepadStates[gx];

        this.fireEvent('gamepadDisconnect', e.gamepad);
    },

    gamepadPoll: function() {
        var gamepadUpdate = navigator.getGamepads();

        for(var gx in this.activeGamepads){
            let ag = this.activeGamepads[gx];

            if(gamepadUpdate[ag.index]){
                ag = gamepadUpdate[ag.index];
            }else{
                this.gamepadDisconnected({gamepad:ag});
                return;
            }

            this.gamepadCheckState(ag);
        }
    },

    getGamepadState: function(gamepad) {
        let state = {
            buttons:{},
            axes:{}
        };

        for(let b in gamepad.buttons){
            state.buttons[b] = gamepad.buttons[b].pressed;
        }
        for(let a in gamepad.axes){
            state.axes[a] = gamepad.axes[a];
        }

        return state;
    },

    gamepadChange: function(gamepad, type, index, newValue, oldValue) {
        let foundMap = false;

        Ext.each(this.mappedGamepads, function(mapped){

            if(mapped.type==='stick'){
                if(mapped.x.gamepadId == gamepad.id && mapped.x.gamepadIndex == gamepad.index && mapped.x.mapType === type && mapped.x.mapIndex === index){
                    foundMap = mapped;
                    newValue = [
                        newValue,
                        this.gamepadStates[mapped.y.gamepadIndex+mapped.y.gamepadId].axes[mapped.y.mapIndex]
                    ];
                    return false;
                }
                if(mapped.y.gamepadId == gamepad.id && mapped.y.gamepadIndex == gamepad.index && mapped.y.mapType === type && mapped.y.mapIndex === index){
                    foundMap = mapped;
                    newValue = [
                        this.gamepadStates[mapped.x.gamepadIndex+mapped.x.gamepadId].axes[mapped.x.mapIndex],
                        newValue
                    ];
                    return false;
                }
            }else{
                if(mapped.gamepadId == gamepad.id && mapped.gamepadIndex == gamepad.index && mapped.mapType === type && mapped.mapIndex === index){
                    foundMap = mapped;
                    return false;
                }
            }
        }, this);

        if(foundMap!==false){
            this.fireEvent('action', foundMap, newValue);
        }
    },

    gamepadAxisChange: function(axisChanges) {
        let stickEvents = {};

        console.log('axis changes');
        console.log(axisChanges);

        for(var a in axisChanges){
            let ag = axisChanges[a];
            console.log('checking for axis mapping');
            console.log(ag);

            Ext.each(this.mappedGamepads, function(mapped){
                console.log(mapped);

                if(mapped.type==='stick'){
                    if(mapped.x && mapped.x.gamepadId == ag.gamepadId && mapped.x.gamepadIndex == ag.gamepadIndex && mapped.x.mapType === 'axis' && mapped.x.mapIndex === ag.mapIndex){
                        console.log('X mapped stick found!');
                        stickEvents[ag.id+ag.index+ag.mapIndex] = {
                            mapped: mapped,
                            newValue: [
                                ag.newValue,
                                this.gamepadStates[mapped.y.gamepadIndex+mapped.y.gamepadId].axes[mapped.y.mapIndex]
                            ]
                        };
                    }
                    if(mapped.y && mapped.y.gamepadId == ag.gamepadId && mapped.y.gamepadIndex == ag.gamepadIndex && mapped.y.mapType === 'axis' && mapped.y.mapIndex === ag.mapIndex){
                        console.log('Y mapped stick found!');
                        stickEvents[ag.id+ag.index+ag.mapIndex] = {
                            mapped: mapped,
                            newValue: [
                                this.gamepadStates[mapped.x.gamepadIndex+mapped.x.gamepadId].axes[mapped.x.mapIndex],
                                ag.newValue
                            ]
                        };
                    }
                }else{
                    if(mapped.gamepadId == ag.gamepadId && mapped.gamepadIndex == ag.gamepadIndex && mapped.mapType === 'axis' && mapped.mapIndex === ag.mapIndex){
                        console.log('axis mapped to item found!');
                        this.fireEvent('action', mapped, newValue);
                    }
                }
            }, this);
        }
        for(var e in stickEvents){
            console.log('fire for stick map');
            console.log(stickEvents[e].newValue[0], stickEvents[e].newValue[1], stickEvents[e].mapped);
            this.fireEvent('action', stickEvents[e].mapped, stickEvents[e].newValue);
        }
    },

    gamepadCheckState: function(gamepad) {
        let gx = gamepad.index+gamepad.id;
        let gs = this.gamepadStates[gx];

        //detect changes!
        let newState = this.getGamepadState(gamepad);
        for(b in newState.buttons){
            if(newState.buttons[b] != gs.buttons[b]){
               this.gamepadChange(gamepad, 'button', b, newState.buttons[b], gs.buttons[b]);
            }
        }
        let axisChanges = [];
        for(a in newState.axes){
            if(Math.abs(newState.axes[a] -gs.axes[a]) >= 0.005){ //for axes detect change more than 0.5%
               axisChanges.push({
                   gamepad:gamepad,
                   gamepadIndex: gamepad.index,
                   gamepadId: gamepad.id,
                   mapIndex:a,
                   newValue: newState.axes[a],
                   oldValue: gs.axes[a]
               });

            }else{
               newState.axes[a] = gs.axes[a];
            }
        }
        if(axisChanges.length > 0){
            this.gamepadAxisChange(axisChanges);
        }
        this.gamepadStates[gx] = newState;
    }

});